### ISSUE TITLE
`bot fmt`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/command-bot#93] opened 2022-07-26 09:23 UTC
should trigger a `cargo +nightly fmt` on the codebase and push back.

**Comment by kianenigma** [comment] 2022-07-28 10:54
Just to make sure I understood your comment, we _can't_ do it already in command-bot, right?

**Comment by joao-paulo-parity** [comment] 2022-07-28 11:07
> Just to make sure I understood your comment, we _can't_ do it already in command-bot, right?

You "can't do" in the sense that the command is not available at the moment, but it's possible to implement it. The `fmt` configuration does not exist yet since we only have `bench-bot` and `try-runtime` configurations as advertised in https://github.com/paritytech/command-bot#pull-request-command-queue.

To create that command we'd do the following

1. Create an `fmt.sh` script in https://github.com/paritytech/pipeline-scripts which formats the code an pushes it to the branch
  - https://github.com/paritytech/pipeline-scripts/blob/892d12e234a62bab6a5c3338ddb1361cbda93a06/bench-bot.sh#L224 can be used as reference for the push
2. Add `fmt` to `commandsConfiguration` https://github.com/paritytech/command-bot/blob/496391d5a65fa593769c0dfe7383b110690e57e0/src/core.ts#L25 which calls the `fmt.sh` script, the same way that https://github.com/paritytech/command-bot/blob/496391d5a65fa593769c0dfe7383b110690e57e0/src/core.ts#L34 works
  - This step might not be necessary **in the future** as per https://github.com/paritytech/command-bot/issues/60#issuecomment-1183396674
3. Use the command as `/cmd queue -c fmt` (or create a `/cmd fmt` alias for it?)

**Comment by mordamax** [comment] 2022-08-02 14:58
Test:
https://github.com/paritytech/substrate/pull/11964/
✅  Fixed formatting https://github.com/paritytech/substrate/pull/11964/commits/cc0ef5d818b3995a6e99fdc90cf62ab21232bd80

however the command-bot probably doesn't expect us to not pass arguments 
so it fails with `/cmd queue -c fmt` or `/cmd queue -c fmt $`
while /cmd queue -c fmt $ 1 works, but usage is weird

**Comment by bkchr** [comment] 2022-08-02 19:08
All of this syntax is very weird. Honestly, I don't care what 1000 bots we got, the syntax should be simple.

A simple `bot fmt` should it be and not any `/cmd queue -c fmt`. 

Can we not just merge bots or make on general thing that reacts to "bot" and then call the appropriate functionality?

**Comment by mordamax** [comment] 2022-08-02 19:16
@bkchr thanks for feedback, I feel your pain. As JP mentioned `(or create a /cmd fmt alias for it?)` of course we can and we need to simplify and this can also be done within #96

**Comment by bkchr** [comment] 2022-08-02 19:25
Still find it weird that there is some difference between `bot` and `/cmd`. Why not have one command for all?

**Comment by mordamax** [comment] 2022-08-02 19:26
@bkchr sorry what `bot` do you mean?

**Comment by mordamax** [comment] 2022-08-02 19:46
yep, that's what command-bot will be essentially.
Remember the try-runtime and benchbot was running differently with separate commands, now they all go through `/cmd queue -c [command-name] $ ...arguments`
now instead of going to add `bot fmt` which would be part of old processbot, it is part of command-bot, which will be one entry point for all types of commands

/cmd queue -c bench $ ...
/cmd queue -c try-runtime $ ...
/cmd queue -c fmt $ ...
etc..
and who knows, may be `bot merge` and `bot rebase` will be migrated here too 

the problem is clear though - the syntax :) and there is a remedy for it #97 💊

**Comment by mordamax** [comment] 2022-08-03 11:30
Closing this meanwhile, as technically it's possible to run, improvements to syntax will be followed up in upcoming issues

**Closed by mordamax** 2022-08-03 11:30 UTC
Labels: enhancement
